name: "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M"
path: "H:/AI/AI_models/LLM/lmstudio-community/DeepSeek-R1-Distill-Qwen-7B-GGUF/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf"
quantization: "int4"
model_type: "gguf"
device: "cuda"
max_length: 512
temperature: 0.7